import Link from "next/link";
import { ArrowRight, BarChart3, Bike, Boxes, Check, Code2, Network, RadioTower, Route, ShieldCheck, Users } from "lucide-react";

const models = [
  { icon: Network, eyebrow: "USE K-DELIVER CAPACITY", title: "We fulfil for you", text: "Send delivery requests into the network. K-Deliver prices, matches and assigns eligible riders or providers while your customer receives one tracking experience.", points: ["Access bicycles and motorcycles", "Overflow capacity when demand spikes", "One price, SLA and tracking layer"] },
  { icon: Code2, eyebrow: "USE K-DELIVER INFRASTRUCTURE", title: "Run your own fleet better", text: "Keep your riders and brand. Use our dispatch, routing, proof of delivery, operations dashboard, APIs and webhooks as your delivery operating system.", points: ["Fleet and rider management", "Dispatch and live tracking", "Provider API and signed webhooks"] },
  { icon: Boxes, eyebrow: "COMBINE BOTH", title: "Operate as a hybrid", text: "Prioritize your own riders, then draw from Kaduna’s wider delivery network when your fleet is unavailable, unsuitable or outside capacity.", points: ["Your fleet remains first-class", "Automatic overflow fulfillment", "Shared performance analytics"] },
];

export default function PartnerPage() { return <main className="partner-page"><header className="topbar"><Link className="brand" href="/"><span>K</span> K-Deliver</Link><nav><Link href="/business">For merchants</Link><Link className="partner-nav-cta" href="/partners/onboard">Join the network</Link></nav></header><section className="partner-hero"><div><p className="kicker">FOR KADUNA DELIVERY COMPANIES</p><h1>More deliveries.<br/><em>Better infrastructure.</em></h1><p>Connect your logistics operation to Kaduna’s open delivery network. Use our riders, use our technology, or combine both.</p><div className="partner-actions"><Link className="primary-action" href="/partners/onboard">Become a network partner <ArrowRight/></Link><Link href="/provider">View provider workspace</Link></div></div><div className="network-visual"><span className="network-core"><Network/><strong>K-Deliver</strong><small>Network layer</small></span><span className="node n1"><Bike/> Shared riders</span><span className="node n2"><Users/> Your fleet</span><span className="node n3"><Code2/> Your systems</span><span className="node n4"><Boxes/> Merchant demand</span></div></section><section className="partner-models"><p className="kicker">CHOOSE HOW YOU CONNECT</p><h2>Built around your operation</h2><div>{models.map(model => { const Icon = model.icon; return <article key={model.title}><Icon/><small>{model.eyebrow}</small><h3>{model.title}</h3><p>{model.text}</p><ul>{model.points.map(point => <li key={point}><Check/> {point}</li>)}</ul></article>; })}</div></section><section className="provider-capabilities"><div><p className="kicker">ONE OPERATING LAYER</p><h2>Infrastructure your team can use from day one.</h2></div><div className="capability-grid"><span><Route/><strong>Dispatch</strong><small>Rank and assign eligible capacity.</small></span><span><RadioTower/><strong>Live operations</strong><small>Track jobs, riders and exceptions.</small></span><span><Code2/><strong>API & webhooks</strong><small>Connect existing systems securely.</small></span><span><ShieldCheck/><strong>Proof & controls</strong><small>PIN, events and audit records.</small></span><span><BarChart3/><strong>Performance</strong><small>Measure acceptance and delivery quality.</small></span></div></section><section className="partner-final"><h2>Already delivering in Kaduna?</h2><p>Bring your operation into the network without giving up your riders or customer relationships.</p><Link className="primary-action" href="/partners/onboard">Start provider onboarding <ArrowRight/></Link></section></main>; }

